version: '3'
services:
    frontend:
        build: ./frontend
        container_name: svelte
        command: npm run dev:ssr
        ports:
            - 5000:5000
            - 35729:35729
        volumes:
            - ./frontend/:/app
            - /app/node_modules
    backend:
        build: ./backend
        container_name: fastapi
        ports:
            - 1337:1337
        volumes:
            - ./backend/:/app/backend
        depends_on:
            - db
            - search
        links:
            - db
    search:
        image: getmeili/meilisearch:v0.21.0
        container_name: meilisearch
        ports:
            - 7700:7700
    db:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: streamchaser
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        restart: always
volumes:
    pgdata:
    node_modules:
